### PR TITLE
Update datetimepicker.da-DK.yml

### PR DESCRIPTION
**Pull request by hallerupnet**

### CODE REVIEW

**Review by ipeshev — APPROVED** [review]

**Comment by tsvetomir** [comment]
Thank you @hallerupnet! I'd like to ask you to sign the [Contributor License Agreement](https://goo.gl/forms/dXc1RaE8le6rVZ0h1) before merging this and the rest PR. You can also group related commits in a single PR.

**Comment by hallerupnet** [comment]
OK, I have signed the agreement. I'm not sure how to group the commits.

**Comment by tsvetomir** [comment]
Not a problem, I'll merge them as they are.

**Comment by tsvetomir** [comment]
Published in v1.26.3

**Pull request merged**
